"use client";
import {useEffect,useRef,useState} from 'react';
import {api,useApi} from '../lib/client';
import {GhostGlyph} from './Ghost';
import {CopyButton} from '../apps/Alerts';
import {setupSnippets} from '../lib/setup-snippets';

const steps=[['Your app','Get your project key'],['JEV','Connect classification'],['Ghost','Choose source access'],['Install','Add the SDK'],['First error','See the full flow']];
export const openSetup=()=>window.dispatchEvent(new Event('s98-open-setup'));
export default function SetupWizard({onClose}) {
  const setup=useApi('setup',{every:4000,on:['event','verdict','settings']});
  const [step,setStep]=useState(0),[service,setService]=useState(''),[framework,setFramework]=useState('react'),[repo,setRepo]=useState(''),[key,setKey]=useState(''),[host,setHost]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[savedKey,setSavedKey]=useState(false);
  const initialized=useRef(false),panel=useRef(null),heading=useRef(null);
  const d=setup.data;
  useEffect(()=>{setHost(window.location.origin);},[]);
  useEffect(()=>{
    if(d&&!initialized.current){initialized.current=true;setStep(d.status==='complete'?0:d.step);setService(d.service);setFramework(d.framework);setRepo(d.repo_path);if(d.host)setHost(d.host);api('setup',{method:'POST',body:{action:'begin',step:d.status==='complete'?0:d.step}}).then(setup.reload).catch(e=>setError(e.message));}
  },[d]);
  useEffect(()=>{heading.current?.focus();},[step,!!d]);
  useEffect(()=>{const previous=document.activeElement;const trap=e=>{if(e.key!=='Tab')return;const controls=[...panel.current.querySelectorAll('button:not(:disabled),input,select,a[href],[tabindex="0"]')].filter(n=>n.getClientRects().length);const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);previous?.focus?.();};},[]);
  async function save(body,next) {setBusy(true);setError('');try{await api('setup',{method:'POST',body});if(next!==undefined)setStep(next);await setup.reload();return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
  async function move(next){const body={step:next,service,framework,host};if(step===2)body.repo_path=repo;if(await save(body,next))setKey('');}
  async function finish(later=false){if(!d){onClose();return;}if(await save({action:later?'later':'complete',step,service,framework,host}))onClose();}
  async function connect(){setBusy(true);setError('');try{await api('setup/jev',{method:'POST',body:key.trim()?{key:key.trim()}:{}});setKey('');setSavedKey(true);await setup.reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
  const snippets=setupSnippets({host,key:d?.project.api_key || '',service,framework,proof:d?.proof_id});
  const download=`${host}${d?.sdk_package || '/downloads/signal98-0.2.0.tgz'}`;
  const verified=d?.jev.lastOkAt&&d?.jev.circuit!=='open',proof=d?.proof;
  return <div className="setup-overlay"><section className="setup-wizard" role="dialog" aria-modal="true" aria-label="Signal98 setup walkthrough" ref={panel}>
    <aside className="setup-rail"><div className="setup-brand"><GhostGlyph size={30} color="#8d79c3"/><span>signal98</span></div><h1>From your first error<br/>to a clearer next step.</h1><ol>{steps.map(([name,hint],i)=><li key={name} className={i===step?'current':i<step?'done':''}><span>{i<step?'✓':i+1}</span><div><strong>{name}</strong><small>{hint}</small></div></li>)}</ol><p>Your app sends events.<br/>JEV assesses them.<br/>Ghost helps you fix them.</p></aside>
    <div className="setup-main"><header><span>SETUP · {step+1} OF {steps.length}</span><button onClick={()=>finish(true)} disabled={busy}>Do this later</button></header>
      <div className="setup-content">{!d?<div><h2 ref={heading} tabIndex={-1}>Loading your setup…</h2>{setup.error&&<p role="alert">{setup.error}<button onClick={setup.reload}>Retry</button></p>}</div>:<>
      {step===0&&<><h2 ref={heading} tabIndex={-1}>Let’s connect your app.</h2><p className="setup-lead">Signal98 has already created a project key for you. There’s no separate Signal98 account to sign up for.</p><label className="setup-field">App name<input value={service} onChange={e=>setService(e.target.value)} maxLength={80} placeholder="my-react-app"/><small>This name identifies the app sending errors.</small></label><label className="setup-field">What are you connecting?<select value={framework} onChange={e=>setFramework(e.target.value)}><option value="react">React / Vite</option><option value="next">Next.js (App Router, Node runtime)</option><option value="script">Website / script tag</option></select></label><div className="setup-key"><div><strong>Your Signal98 project key</strong><CopyButton text={d.project.api_key}>Copy key</CopyButton></div><code>{d.project.api_key}</code><p>This public key goes in your app. It can send events and fetch evaluated feature flags; it does not grant monitor access.</p>{d.project.api_key==='s98_pk_local_dev'&&<small>This is the shared local demo key. Rotate it in Settings before exposing this installation beyond local development.</small>}</div><div className="setup-note">Keep this key separate from the private TypeSafe key in the next step.</div></>}
      {step===1&&<><h2 ref={heading} tabIndex={-1}>Give JEV its connection.</h2><p className="setup-lead">JEV assesses severity, urgency, and likely cause. Get a private API key from your <a href="https://console.typesafe.ai" target="_blank" rel="noreferrer">TypeSafe console ↗</a>, then paste it here.</p><div className={`setup-status ${verified?'ok':''}`}><strong>{verified?'JEV has responded successfully':d.jev.enabled?'A key is configured':'No JEV key connected'}</strong><p>{verified?`Connected to ${d.jev.model}. You can keep using this key.`:d.jev.enabled?'Check the existing connection or enter a replacement key.':'You can also explore Signal98 with clearly labelled keyword-based classification.'}</p></div><form onSubmit={e=>{e.preventDefault();connect();}}><label className="setup-field">{d.jev.enabled?'Replace TypeSafe API key (optional)':'TypeSafe API key'}<input type="password" value={key} onChange={e=>{setKey(e.target.value);setSavedKey(false);}} autoComplete="off" spellCheck={false} placeholder={d.jev.enabled?'Existing key is kept private':'Paste your TypeSafe key'} maxLength={1024}/><small>Stored privately on this Signal98 server. Never included in SDK snippets or browser storage.</small></label><button className="setup-button" disabled={busy||(!key.trim()&&!d.jev.enabled)}>{busy?'Checking connection…':key.trim()?'Save & check key':'Check existing connection'}</button></form>{savedKey&&<p className="setup-success" role="status">Connection verified. Your key is active.</p>}<p className="setup-fine">The connection check makes a small request to TypeSafe using your account.</p></>}
      {step===2&&<><h2 ref={heading} tabIndex={-1}>Give Ghost the right context.</h2><p className="setup-lead">JEV classifies. A separate language model powers Ghost’s conversations and code fixes.</p><div className={`setup-status ${d.ghost_provider!=='template'?'ok':''}`}><strong>{d.ghost_provider==='claude-code'?'Claude Code is available':d.ghost_provider==='openai-compatible'?'Chat model is available':'No chat model connected yet'}</strong><p>{d.ghost_provider==='claude-code'?'Ghost can read your app and prepare isolated code changes.':d.ghost_provider==='openai-compatible'?'Ghost can discuss captured errors. Code-editing runs require Claude Code on the server.':'You can finish installing the SDK now. Configure Claude Code or a chat provider later in Settings → Fix assistant.'}</p></div><label className="setup-field">App repository folder <span>(optional)</span><input value={repo} onChange={e=>setRepo(e.target.value)} placeholder="/path/to/your-react-app" maxLength={1000}/><small>Absolute path on the machine running Signal98. Choose your app’s source folder, not the Signal98 monitor. Code fixes require a Git repository.</small></label><div className="setup-note">Chat is read-only. <strong>Prepare fix</strong> creates proposed changes in a separate checkout; review them before applying.</div></>}
      {step===3&&<><h2 ref={heading} tabIndex={-1}>Install Signal98 in your app.</h2><p className="setup-lead">These snippets already include your project key and app name.</p><label className="setup-field">Monitor address<input value={host} onChange={e=>setHost(e.target.value.replace(/\/$/,''))} type="url"/><small>Use an HTTPS address reachable by your users for a hosted app. localhost only reaches this computer.</small></label>{framework!=='script'&&<Code name="Run in your app’s folder" code={`npm install ${"'"+download.replaceAll("'", "'\"'\"'")+"'"}`}/>}<p className="setup-fine">The SDK package comes from this Signal98 installation, so an npm registry release is not required.</p>{snippets.files.map(f=><Code key={f.name} {...f}/>)}{framework==='next'&&<div className="setup-note">Use both the browser wrapper and server instrumentation. Browser-only capture cannot see server-rendering errors. Merge these into existing files and preserve your other instrumentation.</div>}</>}
      {step===4&&<><h2 ref={heading} tabIndex={-1}>Send your first error.</h2><p className="setup-lead">Add this temporary button to your app, run it, and click <strong>Send test error</strong>. Keep this guide open while you try it.</p><Code name={framework==='script'?'Add to the page body':'Add to a React component'} code={snippets.test}/><div className={`setup-status ${proof?'ok':''}`} aria-live="polite"><strong>{proof?'Your app’s error arrived':'Waiting for your app'}</strong><p>{proof?`Signal98 captured the tagged test from ${service}. Issue #${proof.issue_id} is ${proof.judge_status==='judged'?'classified':'waiting for classification'}.`:'This step only confirms an error carrying this setup’s test marker. Old errors and background demo activity do not count.'}</p>{proof?.judge_status==='judged'&&<p>{proof.judged_by?.startsWith('heuristic')?'Classified by keyword fallback, not JEV.':`Assessed by ${proof.judged_by}.`} Priority: {proof.verdict}.</p>}</div><ol className="setup-next-steps"><li>Open <strong>Conversations</strong> and select the captured issue.</li><li>Read JEV’s assessment and ask your Ghost what happened.</li><li>For a real code defect, choose <strong>Prepare fix</strong>, review the changes, then apply them.</li></ol><p className="setup-fine">This deliberate test proves capture works; it does not represent a real defect that needs fixing. Remove the button when you’re done.</p></>}
      {error&&<p className="setup-error" role="alert">{error}</p>}
      </>}</div>
      <footer><button className="setup-back" disabled={busy||!step||!d} onClick={()=>move(step-1)}>← Back</button><span>{step===1&&!d?.jev.enabled?'JEV is optional during setup':''}</span>{step<4?<button className="setup-button primary" disabled={!d||busy||!service.trim()||!/^https?:\/\//.test(host)} onClick={()=>move(step+1)}>{step===1&&!d?.jev.enabled?'Continue with keyword rules':'Continue'} →</button>:<button className="setup-button primary" disabled={busy} onClick={()=>finish(false)}>{proof?'Open Signal98':'Finish without verification'} →</button>}</footer>
    </div>
  </section></div>;
}
function Code({name,code}){return <div className="setup-code"><div><strong>{name}</strong><CopyButton text={code}>Copy</CopyButton></div><pre><code>{code}</code></pre></div>;}
